name: CD workflow

on:
  push:
    branches:
      - 'master'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inspect
        run: |
          ls -al
          printenv
